services:
  minio:
    image: minio/minio:latest
    container_name: minio
    environment:
      - MINIO_ROOT_USER=root
      - MINIO_ROOT_PASSWORD=root1234
    ports:
      - "9000:9000"   # MinIO API port
      - "9001:9001"   # MinIO console port
    volumes:
      - minio-data:/data
    command: server /data --console-address ":9001"
    networks:
      - compiler-playground-stack

networks:
  compiler-playground-stack:
    external: true

volumes:
  minio-data:
    driver: local
